name: Upload zip on new tag

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Get version
        id: version
        run: echo "VERSION=${GITHUB_REF##refs/tags/}" >> $GITHUB_STATE
      - name: Prepare zip archive
        run: VERSION=${{ env.VERSION }} make archive
      - name: Upload archive to release
        uses: softprops/action-gh-release@v1
        with:
          files: pkg/slack-notify-${{ env.VERSION }}.zip
