name: Tests

on: [push]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run shellcheck
        run: |
          bash --version
          bash -c "time make shellcheck"

  linux:
    name: Bats
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run Bats tests on Ubuntu
        shell: 'script -q -e -c "bash {0}"'
        env:
          TERM: linux
        run: |
          bash --version
          bash -c "time ./test/setup"
          bash -c "time ./test/bats/bin/bats -t test"
